#!/bin/bash

# Useful little script to kill hanging process for node development

set -e
set -u
set -x

port=8080

jobid=`netstat -vanp tcp | grep $port | awk '{ print $9 }'`

test -z "$jobid" && echo "error, no port found" & exit 1

kill -9 $jobid
