#!/bin/bash

# My own bins
if test -d "$HOME/bin"; then PATH="$HOME/bin:$PATH"; fi

# Use newer git
test -d "$HOME/opt/git/" && export PATH=$PATH:$HOME/opt/git/bin
test -f "$HOME/.git-prompt.sh" && source $HOME/.git-prompt.sh

# brew
test -d /opt/homebrew/ && PATH="/opt/homebrew/bin:$PATH"
# Overwrite mac's default, with gnu
if test -d /opt/homebrew; then
    for dir in `echo /opt/homebrew/opt/gnu-*`; do
        test -d $dir/libexec/gnubin && PATH="$dir/libexec/gnubin:$PATH"
    done
fi

# Pip installed packages
if test -d "$HOME/.local/bin"; then PATH="$HOME/.local/bin:$PATH"; fi

# Compiled
if test -d "$HOME/opt/local/bin"; then PATH="$HOME/opt/local/bin:$PATH"; fi

# Gem installed packages
rubyver=2.7.1
if test -d "$HOME/.rbenv/"; then PATH="$HOME/.rbenv/bin:$PATH"; fi
if test -d "$HOME/.rbenv/"; then PATH="$HOME/.rbenv/versions/$rubyver/bin:$PATH"; fi
if test -d "$HOME/.gem/"; then PATH="$HOME/.gem/ruby/$rubyver/bin:$PATH"; fi

rubyver=3.0.0
test -d $HOME/.local/share/gem/ruby/${rubyver}/bin && PATH="$PATH:$HOME/.local/share/gem/ruby/${rubyver}/bin"

# Global bins
if test -d "/opt/bin"; then PATH="/opt/bin:$PATH"; fi
if test -d "/opt/sbin"; then PATH="/opt/sbin:$PATH"; fi
if test -d "/snap/bin"; then PATH="/snap/bin:$PATH"; fi

# databases
if test -d "$HOME/opt/postgres"; then PATH="$HOME/opt/postgres/bin:$PATH"; fi
if test -d "$HOME/opt/redis"; then PATH="$HOME/opt/redis/bin:$PATH"; fi

# # Actually, just overwrite python
# if test -d "$HOME/opt/anaconda3"; then PATH="$HOME/opt/anaconda3/bin:$PATH"; fi
# if test -d "$HOME/opt/miniconda3"; then PATH="$HOME/opt/miniconda3/bin:$PATH"; fi

# Setup conda generally
test -d "$HOME/opt/anaconda3" && CONDA_PREFIX="$HOME/opt/anaconda3"
test -d "$HOME/opt/miniconda3" && CONDA_PREFIX="$HOME/opt/miniconda3"
test -d "$HOME/opt/miniforge" && CONDA_PREFIX="$HOME/opt/miniforge"
test ! -z "$CONDA_PREFIX" && test -d $CONDA_PREFIX/etc/profile.d && source $CONDA_PREFIX/etc/profile.d/conda.sh
unset CONDA_PREFIX  # don't activate by default

# Node Version Manager
export NVM_DIR="$HOME/opt/nvm"
test -s "$NVM_DIR/nvm.sh" && source "$NVM_DIR/nvm.sh" --no-use
test -s "$NVM_DIR/bash_completion" && source "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Rust manager
test -d "$HOME/opt/cargo/" && source $HOME/opt/cargo/env
test -d "$HOME/.cargo/" && source $HOME/.cargo/env

# Go
test -d "$HOME/opt/go" && PATH="$HOME/opt/go/bin:$PATH"
test -d "$HOME/go" && PATH="$HOME/go/bin:$PATH"

# intel license
if test -d $HOME/intel/licenses; then
    for x in $HOME/intel/licenses/*.lic; do
        export INTEL_LICENSE_FILE=$x
    done
    source $HOME/intel/bin/compilervars.sh intel64
fi

# if local hosts file, use it
# TODO Find a better way to make it work with ping and ssh
test -f $HOME/.hosts && export HOSTALIASES=$HOME/.hosts

if [[ "$OSTYPE" == "darwin"* ]]; then
    alias tar=gtar
fi

# sst / opencode
test -d "$HOME/.opencode/" && PATH="$HOME/.opencode/bin:$PATH"

# notes path (zk)
test -d "$HOME/notes" && export ZK_NOTEBOOK_DIR="$HOME/notes"
test -d "$HOME/notes-private" && export ZK_NOTEBOOK_DIR="$HOME/notes-private"

export PATH
