#!/bin/bash

# Set standard editor
export EDITOR=vim

# Easy access
alias dotfiles='cd $HOME/git/dotfiles'

# Git Shortcuts
alias gco='git commit'
alias gca='git commit -a'
alias gad='git add .'
alias gamend='git commit --amend'

alias gd='git diff --color-words'
alias gdc='git diff --cached'
alias gg='git lg'

alias gs='git status -s'
alias gph='git push'
alias gpl='git pull --rebase'

alias ggl='fzf_log'

# Annoying mac uses different ls
if [[ $(uname -s) == Linux ]]
then
    alias ls='ls --color'
else
    alias ls='ls -G'
fi
alias l='ls -lh'

function gitclone {

    url=$1
    out=$2

    if [[ $url != *"@"* && $url != *"http"* ]]
    then
        git clone git@github.com:$url $out
    else
        git clone $1 $out
    fi

}


fzf_log() {
  hash=$(git log --color=always --format="%h%d %an %ae %s %cr" "$@" | fzf | awk '{print $1}')
  echo -n $hash | yank
  git show $hash --color-words
}

# https://junegunn.kr/2016/07/fzf-git
# https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236

# Will return non-zero status if the current directory is not managed by git
is_in_git_repo() {
  git rev-parse HEAD > /dev/null 2>&1
}


fzf-down() {
  fzf --height 50% "$@" --border
}

gh() {
  is_in_git_repo || return
  git log --date=short --format="%C(green)%C(bold)%cd %C(auto)%h%d %s (%an)" --graph --color=always |
  fzf --ansi --no-sort --reverse --multi --bind 'ctrl-s:toggle-sort' \
    --header 'Press CTRL-S to toggle sort' \
    --preview 'grep -o "[a-f0-9]\{7,\}" <<< {} | xargs git show --color=always | head -'$LINES |
  grep -o "[a-f0-9]\{7,\}"
}

alias gc='gitclone' # from bin

# tmux shortcuts
alias tm='tmux'
alias tma='tmux_attach'
alias tml='tmux ls'
alias tmk='tmux kill-session -t $1'
alias tmg='tmux new -s $(basename $(pwd))'

tmux_attach()
{
    # Fuzzy find session if no session is given
    if test ! -z "$1"
    then
        tmux attach -dt $1
    else
        tmux attach -dt `tmux ls | fzf | cut -f1 -d":"`
    fi
}

# tmux clean. Kill all integer tmux sessions
alias tmclean='tmux ls -F "#{session_name}" | while read -r line; do if [[ $line =~ ^-?[0-9]+$  ]]; then tmux kill-session -t $line; fi; done'

# switch git info
function git_use_private {
    git config user.name "Jimmy Charnley Kromann"
    git config user.email "jimmy@charnley.dk"
}

function git_use_novartis {
    git config user.name "Jimmy Charnley Kromann"
    git config user.email "jimmy.kromann@novartis.com"
}

alias cd.='cd ..'
alias cd..='cd ..'
alias cd...='cd ../..'
alias b='cd ..'

alias v='vim'
alias e='vim'
alias vi='vim'
alias p='vim `fzf --preview="bat --color always {}"`'

# easy rsync
alias rs='rsync -azvh --progress'

# download a song easy
alias youtube-audio='youtube-dl --extract-audio --audio-format best'

# spotify
# alias spotplay="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"
# alias spotnext="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"
# alias spotprev="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous"
# alias spotstop="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop"

# Copy vim out to xclip
# alias xp='cat ~/.vbuf | yank'

# AWS Select AWS Profile
function aws_profile {
    export AWS_PROFILE=`cat $HOME/.aws/credentials | grep "\[" | sed -r 's/\[([a-zA-Z]+)\]/\1/' | fzf`
    echo export AWS_PROFILE=$AWS_PROFILE
}

# AWS Expand profile into keys
function aws_profile_expand {
    filename=$HOME/.aws/credentials
    export AWS_ACCESS_KEY_ID=\
    `python3 -c "import configparser; c = configparser.ConfigParser(); c.read('$filename'); print(c['$AWS_PROFILE']['aws_access_key_id'])"`
    export AWS_SECRET_ACCESS_KEY=\
    `python3 -c "import configparser; c = configparser.ConfigParser(); c.read('$filename'); print(c['$AWS_PROFILE']['aws_secret_access_key'])"`
    export AWS_DEFAULT_REGION=\
    `python3 -c "import configparser; c = configparser.ConfigParser(); c.read('$filename'); print(c['$AWS_PROFILE']['aws_default_region'])"`
    echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
}

# Get the last output
# makes vim crash
# PROMPT_COMMAND='LAST="`cat /tmp/x`"; exec >/dev/tty; exec > >(tee /tmp/x)'

# https://twitter.com/ctrlshifti/status/1160812366293901314
alias please="sudo"

# make directory and change directory
function take {
  mkdir -p $1
  cd $1
}

# Can't remmeber all the different extraction commands
extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xvjf $1 ;;
            *.tar.gz)    tar xvzf $1 ;;
            *.bz2)       bunzip2 $1 ;;
            *.rar)       unrar x $1 ;;
#            *.gz)        gunzip $1 ;;
            *.gz)        tar xvf $1 ;;
            *.tar)       tar xvf $1 ;;
            *.tbz2)      tar xvjf $1 ;;
            *.tgz)       tar xvzf $1 ;;
            *.zst)       tar -I zstd xvzf $1 ;;
            *.zip)       unzip $1 ;;
            *.Z)         uncompress $1 ;;
            *.7z)        7z x $1 ;;
            *.tar.*)     tar xvf $1 ;;
            *)           echo "don't know how to extract '$1'..." ;;
        esac
    else
        echo "'$1' is not a valid file!"
    fi
}

# Get code snippets
cheat()
{
    where="$1"; shift
    IFS=+ curl "https://cht.sh/$where/ $*"
}

# Get outward facing ip
alias myip='echo $(curl -s https://api.ipify.org)'

# fun
alias emoji_shrug='echo -n "¯\_(ツ)_/¯" | yank'
alias emoji_run='echo -n "ᕕ( ᐛ )ᕗ" | yank'

# if local
test -f $HOME/.bash_aliases.local && source $HOME/.bash_aliases.local

# slurm specific commands
if test -x "$(command -v sinfo)"; then
    alias s_idle='sinfo | grep idle'
    alias s_busy='sinfo | grep alloc; sinfo | grep mix'

    alias q='squeue -u $USER'
    alias ql='squeue | grep $USER | wc -l'

    # http://slurm.schedmd.com/squeue.html
    alias qs='squeue -o "%.10i %.9P %.8u %.10j %.12M %.5D %.4C %R"'
fi


