#!/bin/bash

# set -x
set -e
set -u

if test ! -f $1
then
    echo "$1 does not exist"
    exit 1
fi

# TODO Check if this is a git
# TODO Check if git has pre-commit

filetype="${1#*.}"

if test $filetype == "py"
then
    isort $1
    black $1
    exit 0
else
    npx prettier --write $1
    exit $?
fi
