#!/bin/bash

# set -x
set -e
set -u

if test ! -f $1
then
    echo "$1 does not exist"
    exit 1
fi

filetype="${1#*.}"

if test $filetype == "py"
then
    black $1
    exit 0
else
    npx prettier --write $1
    exit $?
fi
